authority=https://login.microsoftonline.com/f2a29c7e-5230-41d3-b5d1-4b6e2c4e6b7c/
client_id=726e781b-6215-4119-a4cd-9d43ef16c606
secret=6Az8Q~TLETtWAA01MfJcx2H1Oxi-1mXj2mwAAdmI
scope=https://management.azure.com/.default