AUTHORITY=https://login.microsoftonline.com/f2a29c7e-5230-41d3-b5d1-4b6e2c4e6b7c/
CLIENT_ID=726e781b-6215-4119-a4cd-9d43ef16c606
SECRET=KPx8Q~3_SKvRudW3L9x5Bvc5qN9bN8vs~22OCa7Y

SCOPE=https://management.azure.com/.default