# this class is a utility to help make sense of the
# 'pattern_disposition' field in API responses.
# Crowdstrike Falcon encodes the actions that the EDR
# took in a bitmask field. Thankfully, the mask components
# are documented so we can create this utility.
# Reference:https://falcon.us-2.crowdstrike.com/documentation/page/e3ce0b24/events-data-dictionary#ModuleBlockedEventWithPatternId
PREVENT_KILL_PROCESS = 16
PREVENT_QUARANTINE_FILE = 128
PREVENT_KILL_PARENT = 512
PREVENT_OPERATION_BLOCKED = 1024
PREVENT_BLOCK_PROCESS = 2048
PREVENT_REG_OPERATION_BLOCKED = 4096
PREVENT_FS_OPERATION_BLOCKED = 32768
PREVENT_HANDLE_OPERATION_DOWNGRADED = 65536
PREVENT_SUSPEND_PARENT = 1048576
PREVENT_SUSPEND_PROCESS = 524288

ALL_PREVENT = (
    PREVENT_KILL_PROCESS
    | PREVENT_QUARANTINE_FILE
    | PREVENT_KILL_PARENT
    | PREVENT_OPERATION_BLOCKED
    | PREVENT_BLOCK_PROCESS
    | PREVENT_REG_OPERATION_BLOCKED
    | PREVENT_FS_OPERATION_BLOCKED
    | PREVENT_HANDLE_OPERATION_DOWNGRADED
    | PREVENT_SUSPEND_PARENT
    | PREVENT_SUSPEND_PROCESS
)

MODIFY_POLICY_DISABLED = 256
MODIFY_CRITICAL_PROCESS_DISABLED = 8192
MODIFY_BOOTUP_SAFEGUARD_ENABLED = 16384
MODIFY_KILL_ACTION_FAILED = 131072
MODIFY_BLOCKING_UNSUPPORTED_OR_DISABLED = 262144
MODIFY_RESPONSE_ACTION_ALREADY_APPLIED = 2097152
MODIFY_RESPONSE_ACTION_FAILED = 4194304

ALL_MODIFY = (
    MODIFY_POLICY_DISABLED
    | MODIFY_CRITICAL_PROCESS_DISABLED
    | MODIFY_BOOTUP_SAFEGUARD_ENABLED
    | MODIFY_KILL_ACTION_FAILED
    | MODIFY_BLOCKING_UNSUPPORTED_OR_DISABLED
    | MODIFY_RESPONSE_ACTION_ALREADY_APPLIED
    | MODIFY_RESPONSE_ACTION_FAILED
)


def is_prevented(pattern_disposition: int) -> bool:
    return (
        pattern_disposition & ALL_PREVENT > 0 and pattern_disposition & ALL_MODIFY == 0
    )
